[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info

# ----------------------------
# SSH service
# ----------------------------
[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/ssh_stdout.log
stderr_logfile=/var/log/ssh_stderr.log
user=root

# ----------------------------
# Jupyter service
# ----------------------------
[program:jupyter]
command=/usr/local/bin/start-notebook.py \
    --NotebookApp.password=${JUPYTER_PASSWORD_HASHED} \
    --NotebookApp.base_url=/mldd \
    --NotebookApp.ip=0.0.0.0 \
    --NotebookApp.port=${JUPYTER_PORT} \
    --NotebookApp.notebook_dir=/home/jovyan
autostart=true
autorestart=true
stdout_logfile=/var/log/jupyter_stdout.log
stderr_logfile=/var/log/jupyter_stderr.log
user=jovyan
