[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[unix_http_server]
file=/var/run/supervisor.sock   ; path to the socket

[program:sshd]
command=/usr/sbin/sshd -D -e
autostart=true
autorestart=false
stdout_logfile=/var/log/sshd_stdout.log
stderr_logfile=/var/log/sshd_stderr.log

[program:notebook]
command=/usr/local/bin/start-notebook.sh
priority=20
autostart=true
autorestart=true
user=jovyan
